version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.13.0
    #build: .
    container_name: data
    environment:
      - USER=git
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__DB_TYPE__PATH=sqlite3
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "3222:22"
